//! Registry of workflow, task, update and actor handlers.
//!
//! Handlers are registered manually or, with the `auto-register` feature,
//! collected from the SDK's macros.
//!
//! ## Usage
//!
//! ### Auto-registration (recommended)
//!
//! ```rust,no_run
//! use orcher_sdk::prelude::*;
//!
//! #[task] // Submits a registration entry to `inventory`.
//! async fn greet(_ctx: TaskContext, name: String) -> Result<String> {
//!     Ok(format!("Hello, {name}"))
//! }
//!
//! #[tokio::main]
//! async fn main() -> Result<()> {
//!     // The builder collects every submitted entry.
//!     let worker = Worker::builder()
//!         .server_url("http://localhost:50051")
//!         .build()
//!         .await?;
//!     worker.run().await
//! }
//! ```
//!
//! ### Manual registration
//!
//! ```rust
//! use orcher_sdk::worker::registry::{Registry, TaskHandler, WorkflowHandler};
//! use std::sync::Arc;
//!
//! let mut registry = Registry::new();
//!
//! // Handlers take and return payloads; this task echoes its input.
//! registry.register_task("echo", TaskHandler {
//!     name: "echo".to_string(),
//!     handler: Some(Arc::new(|_ctx, input| Box::pin(async move { Ok(input) }))),
//! });
//! registry.register_workflow("my_workflow", WorkflowHandler {
//!     name: "my_workflow".to_string(),
//!     handler: Some(Arc::new(|_ctx, input| Box::pin(async move { Ok(input) }))),
//! });
//!
//! assert!(registry.has_task("echo"));
//! assert!(registry.has_workflow("my_workflow"));
//! ```

use std::collections::HashMap;
use std::sync::RwLock;

#[cfg(feature = "auto-register")]
use crate::worker::registration::{
    ActorHandlerRegistration, TaskRegistration, WorkflowRegistration,
};

#[cfg(feature = "auto-register")]
use once_cell::sync::Lazy;

/// Process-wide registry of auto-registered actor operation handlers.
///
/// The `#[operations]` macro generates constructor functions that add each
/// operation's handler here at program startup. Tasks, workflows and updates
/// are collected through `inventory` instead. The
/// [`WorkerBuilder`](crate::worker::WorkerBuilder) copies these entries into
/// the worker's [`Registry`] when it is created.
///
/// The `RwLock` makes access thread-safe. Registration runs in `#[ctor::ctor]`
/// functions before `main`, so in practice there is no contention.
///
/// # Example
///
/// ```text
/// // Shape of a constructor function generated by `#[operations]`:
/// #[::orcher_sdk::ctor::ctor]
/// fn __orcher_register_actor_handler_Counter_increment() {
///     ::orcher_sdk::worker::registry::GLOBAL_REGISTRY
///         .write()
///         .unwrap()
///         .register_actor_handler_direct(ActorHandlerRegistration { ... });
/// }
/// ```
#[cfg(feature = "auto-register")]
pub static GLOBAL_REGISTRY: Lazy<RwLock<GlobalRegistry>> = Lazy::new(|| {
    tracing::debug!("Initializing global auto-registration registry");
    RwLock::new(GlobalRegistry::new())
});

/// Storage behind [`GLOBAL_REGISTRY`].
///
/// Kept separate from [`Registry`] to avoid circular dependencies and to give
/// generated registration code a smaller interface.
#[cfg(feature = "auto-register")]
#[derive(Debug, Default)]
pub struct GlobalRegistry {
    /// Always empty: tasks are collected through `inventory`.
    tasks: Vec<TaskRegistration>,

    /// Always empty: workflows are collected through `inventory`.
    workflows: Vec<WorkflowRegistration>,

    actor_handlers: Vec<ActorHandlerRegistration>,
}

#[cfg(feature = "auto-register")]
impl GlobalRegistry {
    /// Creates an empty registry.
    pub fn new() -> Self {
        Self {
            tasks: Vec::new(),
            workflows: Vec::new(),
            actor_handlers: Vec::new(),
        }
    }

    /// Does nothing; tasks are registered through `inventory`.
    ///
    /// Kept so that code calling it still compiles.
    #[deprecated(note = "Tasks are now registered via inventory")]
    pub fn register_task_direct(&mut self, _registration: TaskRegistration) {
        tracing::debug!("Task registration via GlobalRegistry is deprecated - use inventory");
    }

    /// Does nothing; workflows are registered through `inventory`.
    ///
    /// Kept so that code calling it still compiles.
    #[deprecated(note = "Workflows are now registered via inventory")]
    pub fn register_workflow_direct(&mut self, _registration: WorkflowRegistration) {
        tracing::debug!("Workflow registration via GlobalRegistry is deprecated - use inventory");
    }

    /// Adds an actor operation handler.
    ///
    /// Called by the `#[ctor::ctor]` functions that the `#[operations]` macro
    /// generates.
    pub fn register_actor_handler_direct(&mut self, registration: ActorHandlerRegistration) {
        tracing::debug!(
            actor = registration.actor_name,
            operation = registration.operation_name,
            "Auto-registering actor handler to global registry"
        );
        self.actor_handlers.push(registration);
    }

    /// Task registrations; always empty, see [`GlobalRegistry::register_task_direct`].
    pub fn tasks(&self) -> &[TaskRegistration] {
        &self.tasks
    }

    /// Workflow registrations; always empty, see
    /// [`GlobalRegistry::register_workflow_direct`].
    pub fn workflows(&self) -> &[WorkflowRegistration] {
        &self.workflows
    }

    /// Number of task registrations; always zero.
    pub fn task_count(&self) -> usize {
        self.tasks.len()
    }

    /// Number of workflow registrations; always zero.
    pub fn workflow_count(&self) -> usize {
        self.workflows.len()
    }

    /// All registered actor operation handlers.
    pub fn actor_handlers(&self) -> &[ActorHandlerRegistration] {
        &self.actor_handlers
    }

    /// Number of registered actor operation handlers.
    pub fn actor_handler_count(&self) -> usize {
        self.actor_handlers.len()
    }
}

/// A worker's handlers, looked up by name.
///
/// Holds workflow, task and update handlers and, with the `auto-register`
/// feature, actor definitions and actor operation handlers.
#[derive(Debug, Default)]
pub struct Registry {
    /// Workflow handlers by workflow name.
    pub workflows: HashMap<String, WorkflowHandler>,

    /// Task handlers by task name.
    pub tasks: HashMap<String, TaskHandler>,

    /// Update handlers by update name.
    pub updates: HashMap<String, UpdateHandler>,

    /// Actor definitions by actor name. Filled only from definitions submitted
    /// by hand; macro-declared actors appear only in `actor_handlers`.
    #[cfg(feature = "auto-register")]
    pub actors: HashMap<String, crate::actor::definition::ActorDefinition>,

    /// Actor operation handlers by actor name, then operation name.
    #[cfg(feature = "auto-register")]
    pub actor_handlers: HashMap<String, HashMap<String, ActorHandlerRegistration>>,
}

/// A registered workflow: its name and, when available, its handler.
#[derive(Clone)]
pub struct WorkflowHandler {
    /// Workflow name.
    pub name: String,

    /// The handler, if one was supplied.
    #[cfg(feature = "auto-register")]
    pub handler: Option<crate::worker::registration::WorkflowHandlerFn>,
}

/// A registered task: its name and, when available, its handler.
#[derive(Clone)]
pub struct TaskHandler {
    /// Task name.
    pub name: String,

    /// The handler, if one was supplied.
    #[cfg(feature = "auto-register")]
    pub handler: Option<crate::worker::registration::TaskHandlerFn>,
}

/// A registered update handler: its name and, when available, its function.
#[derive(Clone)]
pub struct UpdateHandler {
    /// Update name.
    pub name: String,

    /// The handler, if one was supplied.
    #[cfg(feature = "auto-register")]
    pub handler: Option<crate::worker::registration::UpdateHandlerFn>,
}

impl std::fmt::Debug for WorkflowHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WorkflowHandler")
            .field("name", &self.name)
            .finish()
    }
}

impl std::fmt::Debug for TaskHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TaskHandler")
            .field("name", &self.name)
            .finish()
    }
}

impl std::fmt::Debug for UpdateHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UpdateHandler")
            .field("name", &self.name)
            .finish()
    }
}

impl Registry {
    /// Creates an empty registry.
    pub fn new() -> Self {
        Self {
            workflows: HashMap::new(),
            tasks: HashMap::new(),
            updates: HashMap::new(),
            #[cfg(feature = "auto-register")]
            actors: HashMap::new(),
            #[cfg(feature = "auto-register")]
            actor_handlers: HashMap::new(),
        }
    }

    /// Registers a workflow handler under `name`, replacing any previous one.
    ///
    /// # Example
    ///
    /// ```rust
    /// use orcher_sdk::worker::registry::{Registry, WorkflowHandler};
    /// use std::sync::Arc;
    ///
    /// let mut registry = Registry::new();
    /// registry.register_workflow("order_workflow", WorkflowHandler {
    ///     name: "order_workflow".to_string(),
    ///     handler: Some(Arc::new(|_ctx, input| Box::pin(async move { Ok(input) }))),
    /// });
    /// assert_eq!(registry.workflow_names(), ["order_workflow"]);
    /// ```
    pub fn register_workflow(&mut self, name: impl Into<String>, handler: WorkflowHandler) {
        let name = name.into();
        tracing::debug!(workflow = %name, "Registering workflow handler");
        self.workflows.insert(name, handler);
    }

    /// Registers a task handler under `name`, replacing any previous one.
    ///
    /// # Example
    ///
    /// ```rust
    /// use orcher_sdk::worker::registry::{Registry, TaskHandler};
    /// use std::sync::Arc;
    ///
    /// let mut registry = Registry::new();
    /// registry.register_task("process_payment", TaskHandler {
    ///     name: "process_payment".to_string(),
    ///     handler: Some(Arc::new(|_ctx, input| Box::pin(async move { Ok(input) }))),
    /// });
    /// assert_eq!(registry.task_names(), ["process_payment"]);
    /// ```
    pub fn register_task(&mut self, name: impl Into<String>, handler: TaskHandler) {
        let name = name.into();
        tracing::debug!(task = %name, "Registering task handler");
        self.tasks.insert(name, handler);
    }

    /// Returns the workflow handler registered under `name`.
    pub fn get_workflow(&self, name: &str) -> Option<&WorkflowHandler> {
        self.workflows.get(name)
    }

    /// Returns the task handler registered under `name`.
    pub fn get_task(&self, name: &str) -> Option<&TaskHandler> {
        self.tasks.get(name)
    }

    /// Names of all registered workflows, in no particular order.
    pub fn workflow_names(&self) -> Vec<&str> {
        self.workflows.keys().map(|s| s.as_str()).collect()
    }

    /// Names of all registered tasks, in no particular order.
    pub fn task_names(&self) -> Vec<&str> {
        self.tasks.keys().map(|s| s.as_str()).collect()
    }

    /// Whether a workflow is registered under `name`.
    pub fn has_workflow(&self, name: &str) -> bool {
        self.workflows.contains_key(name)
    }

    /// Whether a task is registered under `name`.
    pub fn has_task(&self, name: &str) -> bool {
        self.tasks.contains_key(name)
    }

    /// Registers an update handler under `name`, replacing any previous one.
    pub fn register_update(&mut self, name: impl Into<String>, handler: UpdateHandler) {
        let name = name.into();
        tracing::debug!(update = %name, "Registering update handler");
        self.updates.insert(name, handler);
    }

    /// Returns the update handler registered under `name`.
    pub fn get_update(&self, name: &str) -> Option<&UpdateHandler> {
        self.updates.get(name)
    }

    /// Names of all registered update handlers, in no particular order.
    pub fn update_names(&self) -> Vec<&str> {
        self.updates.keys().map(|s| s.as_str()).collect()
    }

    /// Whether an update handler is registered under `name`.
    pub fn has_update(&self, name: &str) -> bool {
        self.updates.contains_key(name)
    }

    /// Number of registered workflows.
    pub fn workflow_count(&self) -> usize {
        self.workflows.len()
    }

    /// Number of registered tasks.
    pub fn task_count(&self) -> usize {
        self.tasks.len()
    }

    /// Number of registered update handlers.
    pub fn update_count(&self) -> usize {
        self.updates.len()
    }

    /// Number of actor definitions.
    ///
    /// Counts only definitions submitted by hand; use
    /// [`Registry::actor_handler_count`] for macro-declared actors.
    #[cfg(feature = "auto-register")]
    pub fn actor_count(&self) -> usize {
        self.actors.len()
    }

    /// Names of all actor definitions, in no particular order.
    #[cfg(feature = "auto-register")]
    pub fn actor_names(&self) -> Vec<&str> {
        self.actors.keys().map(|s| s.as_str()).collect()
    }

    /// Returns the actor definition registered under `name`.
    #[cfg(feature = "auto-register")]
    pub fn get_actor(&self, name: &str) -> Option<&crate::actor::definition::ActorDefinition> {
        self.actors.get(name)
    }

    /// Whether an actor definition is registered under `name`.
    #[cfg(feature = "auto-register")]
    pub fn has_actor(&self, name: &str) -> bool {
        self.actors.contains_key(name)
    }

    /// Actor operation handlers, by actor name and then operation name.
    #[cfg(feature = "auto-register")]
    pub fn actor_handlers(&self) -> &HashMap<String, HashMap<String, ActorHandlerRegistration>> {
        &self.actor_handlers
    }

    /// Number of actor operation handlers, across all actors.
    #[cfg(feature = "auto-register")]
    pub fn actor_handler_count(&self) -> usize {
        self.actor_handlers.values().map(|ops| ops.len()).sum()
    }

    /// Collects every auto-registered handler into this registry.
    ///
    /// Runs the task, workflow and update registration functions submitted to
    /// `inventory`, copies the actor operation handlers from [`GLOBAL_REGISTRY`],
    /// and collects actor definitions from `inventory`.
    ///
    /// [`WorkerBuilder::new`](crate::worker::WorkerBuilder::new) calls this.
    ///
    /// # Example
    ///
    /// ```rust
    /// use orcher_sdk::prelude::*;
    /// use orcher_sdk::worker::Registry;
    ///
    /// #[task]
    /// async fn greet(_ctx: TaskContext, name: String) -> Result<String> {
    ///     Ok(format!("Hello, {name}"))
    /// }
    ///
    /// let mut registry = Registry::new();
    /// registry.collect_from_global_registry();
    ///
    /// assert!(registry.has_task("greet"));
    /// println!("Auto-registered {} workflows", registry.workflow_count());
    /// ```
    #[cfg(feature = "auto-register")]
    pub fn collect_from_global_registry(&mut self) {
        let task_registrations: Vec<_> =
            inventory::iter::<crate::worker::registration::TaskRegistration>()
                .copied()
                .collect();

        let task_count = task_registrations.len();
        for registration in task_registrations {
            tracing::debug!("Invoking task registration function");
            registration.register(self);
        }

        let workflow_registrations: Vec<_> =
            inventory::iter::<crate::worker::registration::WorkflowRegistration>()
                .copied()
                .collect();

        let workflow_count = workflow_registrations.len();
        for registration in workflow_registrations {
            tracing::debug!("Invoking workflow registration function");
            registration.register(self);
        }

        let update_registrations: Vec<_> =
            inventory::iter::<crate::worker::registration::UpdateRegistration>()
                .copied()
                .collect();

        let update_count = update_registrations.len();
        for registration in update_registrations {
            tracing::debug!("Invoking update handler registration function");
            registration.register(self);
        }

        // Actor operation handlers come from GLOBAL_REGISTRY, not `inventory`.
        #[cfg(feature = "auto-register")]
        {
            let global = GLOBAL_REGISTRY
                .read()
                .expect("Failed to acquire read lock on GLOBAL_REGISTRY");

            let _actor_handler_count = global.actor_handlers().len();
            for handler_registration in global.actor_handlers() {
                tracing::debug!(
                    actor = handler_registration.actor_name,
                    operation = handler_registration.operation_name,
                    "Collecting actor handler from global registry"
                );

                self.actor_handlers
                    .entry(handler_registration.actor_name.to_string())
                    .or_default()
                    .insert(
                        handler_registration.operation_name.to_string(),
                        handler_registration.clone(),
                    );
            }
        }

        // Actor definitions are collected through `inventory`.
        let actors: Vec<_> = inventory::iter::<crate::actor::definition::ActorDefinition>()
            .cloned()
            .collect();

        let actor_count = actors.len();
        for actor_def in actors {
            tracing::debug!(
                actor = actor_def.actor_name(),
                operations = actor_def.operation_count(),
                "Collecting actor from inventory"
            );

            self.actors
                .insert(actor_def.actor_name().to_string(), actor_def);
        }

        tracing::info!(
            tasks = task_count,
            workflows = workflow_count,
            updates = update_count,
            actors = actor_count,
            "Collected and registered handlers from inventory"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_new() {
        let registry = Registry::new();
        assert_eq!(registry.workflow_count(), 0);
        assert_eq!(registry.task_count(), 0);
    }

    #[test]
    fn test_register_workflow() {
        let mut registry = Registry::new();
        let handler = WorkflowHandler {
            name: "test_workflow".to_string(),
            #[cfg(feature = "auto-register")]
            handler: None,
        };

        registry.register_workflow("test_workflow", handler);

        assert_eq!(registry.workflow_count(), 1);
        assert!(registry.has_workflow("test_workflow"));
        assert!(!registry.has_workflow("unknown"));
    }

    #[test]
    fn test_register_task() {
        let mut registry = Registry::new();
        let handler = TaskHandler {
            name: "test_task".to_string(),
            #[cfg(feature = "auto-register")]
            handler: None,
        };

        registry.register_task("test_task", handler);

        assert_eq!(registry.task_count(), 1);
        assert!(registry.has_task("test_task"));
        assert!(!registry.has_task("unknown"));
    }

    #[test]
    fn test_get_handlers() {
        let mut registry = Registry::new();

        let wf_handler = WorkflowHandler {
            name: "my_workflow".to_string(),
            #[cfg(feature = "auto-register")]
            handler: None,
        };
        let task_handler = TaskHandler {
            name: "my_task".to_string(),
            #[cfg(feature = "auto-register")]
            handler: None,
        };

        registry.register_workflow("my_workflow", wf_handler);
        registry.register_task("my_task", task_handler);

        assert!(registry.get_workflow("my_workflow").is_some());
        assert!(registry.get_task("my_task").is_some());
        assert!(registry.get_workflow("unknown").is_none());
        assert!(registry.get_task("unknown").is_none());
    }

    #[test]
    fn test_list_names() {
        let mut registry = Registry::new();

        registry.register_workflow(
            "workflow1",
            WorkflowHandler {
                name: "workflow1".to_string(),
                #[cfg(feature = "auto-register")]
                handler: None,
            },
        );
        registry.register_workflow(
            "workflow2",
            WorkflowHandler {
                name: "workflow2".to_string(),
                #[cfg(feature = "auto-register")]
                handler: None,
            },
        );
        registry.register_task(
            "task1",
            TaskHandler {
                name: "task1".to_string(),
                #[cfg(feature = "auto-register")]
                handler: None,
            },
        );

        let workflow_names = registry.workflow_names();
        let task_names = registry.task_names();

        assert_eq!(workflow_names.len(), 2);
        assert_eq!(task_names.len(), 1);
        assert!(workflow_names.contains(&"workflow1"));
        assert!(workflow_names.contains(&"workflow2"));
        assert!(task_names.contains(&"task1"));
    }

    #[cfg(feature = "auto-register")]
    #[test]
    fn test_collect_from_global_registry() {
        let mut registry = Registry::new();

        // What gets collected depends on the test binary; this only checks
        // that collection does not panic.
        registry.collect_from_global_registry();

        println!(
            "Collected {} tasks and {} workflows from global registry",
            registry.task_count(),
            registry.workflow_count()
        );
    }

    #[test]
    fn test_registry_default() {
        let registry = Registry::default();
        assert_eq!(registry.workflow_count(), 0);
        assert_eq!(registry.task_count(), 0);
    }
}
